openapi: 3.0.0
info:
  description: |
    This is simple client API
  version: "1.0.0"
  title: User Service
  contact:
    email: vasiliev.maxim@gmail.com
servers:
  - description: VM User Service
    url: http://vm-user-service.maximserver/
tags:
  - name: user
    description: Operations about user
paths:
  /user/{userId}:
    parameters:
    - name: userId
      in: path
      description: ID of user
      required: true
      schema:
        type: integer
        format: int64
    post:
      tags:
        - user
      summary: Create user
      description: If user is not found, create new user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
            examples:
              sample-user:
                summary: Example
                value:
                  username: johndoe589
                  firstName: John
                  lastName: Doe
                  email: bestjohn@doe.com
                  phone: '+71002003040'
        description: Created user object
        required: true
      responses:
        '204':
          description: User Created
        '409':
          description: User already exists
    get:
      tags:
        - user
      description: Returns a user based on a single ID, if the user does not have access to the user
      operationId: find user by id
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: user not found
    delete:
      tags:
        - user
      description: deletes a single user based on the ID supplied
      operationId: deleteUser
      responses:
        '204':
          description: user deleted
        '404':
          description: user not found
    put:
      tags:
        - user
      description: Update user with User ID supplied
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
            examples:
              sample-user:
                summary: Example
                value:
                  firstName: Julie
                  lastName: Doe
                  email: bestjohn@doe.com
                  phone: '+71004242424'

      responses:
        '200':
          description: User updated
        '404':
          description: User not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
        username:
          type: string
          maxLength: 256
          example: johndoe589
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        avatar:
          type: string
          example: https://example.com/avatar.jpg
        sex:
          type: number
          example: 1
        verified:
          type: boolean
          example: false
        birthday:
          type: string
          pattern: '^(0[1-9]|[1-2][0-9]|3[0-1])\\.(0[1-9]|1[0-2])\\.\\d{4}$'
          example: 19.03.1982
        email:
          type: string
          format: email
          example: bestjohn@doe.com
        phone:
          type: string
          format: phone
          example: '+71002003040'
    UpdateUser:
      type: object
      properties:
        username:
          type: string
          maxLength: 256
          example: johndoe589
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        avatar:
          type: string
          example: https://example.com/avatar.jpg
        sex:
          type: number
          example: 1
        verified:
          type: boolean
          example: false
        birthday:
          type: string
          pattern: '^(0[1-9]|[1-2][0-9]|3[0-1])\\.(0[1-9]|1[0-2])\\.\\d{4}$'
          example: 19.03.1982
        email:
          type: string
          format: email
          example: bestjohn@doe.com
        phone:
          type: string
          format: phone
          example: '+71002003040'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string